<?php

namespace App\Http\Controllers;

use App\Models\Strategy;
use Illuminate\Http\Request;
use PhpOffice\PhpPresentation\PhpPresentation;
use PhpOffice\PhpPresentation\IOFactory;
use PhpOffice\PhpPresentation\Style\Color;
use PhpOffice\PhpPresentation\Style\Alignment;
use PhpOffice\PhpPresentation\Slide\Background\Color as BgColor;

class StrategyController extends Controller
{
    // ARGB color constants
    private const NAVY  = 'FF003470';
    private const PINK  = 'FFFC54AA';
    private const WHITE = 'FFFFFFFF';
    private const DARK  = 'FF1A1A2E';

    public function downloadSlides(string $id)
    {
        $strategy = Strategy::findOrFail($id);

        // Authorization: must belong to the active client for the current user
        $user = auth()->user();
        if ($user->isClientUser()) {
            $client = $user->profile?->client;
        } else {
            $clientId = session('active_client_id');
            $client = $clientId ? \App\Models\Client::find($clientId) : null;
        }
        abort_unless($client && $strategy->client_id === $client->id, 403);

        if (!class_exists('ZipArchive')) {
            abort(500, 'ZipArchive PHP extension is required to generate PPTX files.');
        }

        try {
            $slides = $this->parseSlides($strategy->generated_document ?? '', $client->name);

            $prs = new PhpPresentation();
            $prs->getDocumentProperties()
                ->setTitle("{$client->name} Strategy")
                ->setDescription('Generated by Coral');

            // Remove the default blank slide
            $prs->removeSlideByIndex(0);

            foreach ($slides as $i => $slideData) {
                $this->buildSlide($prs, $slideData, $i === 0, count($slides));
            }

            $path = storage_path('app/tmp_' . uniqid() . '.pptx');
            $writer = IOFactory::createWriter($prs, 'PowerPoint2007');
            $writer->save($path);

            $filename = \Illuminate\Support\Str::slug($client->name . ' Strategy') . '.pptx';
            return response()->download($path, $filename, [
                'Content-Type' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
            ])->deleteFileAfterSend(true);
        } catch (\Throwable $e) {
            \Illuminate\Support\Facades\Log::error('PPTX generation failed', [
                'error' => $e->getMessage(),
                'trace' => $e->getTraceAsString(),
            ]);
            abort(500, 'Slide generation failed: ' . $e->getMessage());
        }
    }

    private function parseSlides(string $doc, string $clientName): array
    {
        // Use AI to extract slide content
        try {
            $prompt = "You are converting a marketing strategy document into a slide deck for {$clientName}.

Extract slide content from this strategy document and return a JSON array of slides. Each slide has:
- \"title\": slide title (string)
- \"bullets\": array of bullet point strings (3-6 bullets max per slide)
- \"type\": \"title\" (first slide only) or \"content\"

Create 8-12 slides covering the key sections. First slide is the title slide with just title and a subtitle bullet.
The slides should cover: Overview, Market Opportunity, Target Audience, Goals & KPIs, Channel Strategy, Content Strategy, Timeline, Next Steps.

Return ONLY valid JSON, no markdown, no explanation.

STRATEGY DOCUMENT:
" . mb_substr($doc, 0, 6000);

            $response = app(\Anthropic\Client::class)->messages->create(
                maxTokens: 2000,
                messages: [['role' => 'user', 'content' => $prompt]],
                model: 'claude-haiku-4-5-20251001',
            );
            $json = $response->content[0]->text ?? '[]';
            // Strip markdown fences if present
            $json = preg_replace('/^```(?:json)?\s*/m', '', $json);
            $json = preg_replace('/\s*```$/m', '', $json);
            $slides = json_decode(trim($json), true);
            if (is_array($slides) && count($slides) > 0) {
                return $slides;
            }
        } catch (\Exception $e) {
            // Fall through to basic parse
        }

        // Fallback: split by markdown headers
        return $this->basicParse($doc, $clientName);
    }

    private function basicParse(string $doc, string $clientName): array
    {
        $slides = [
            ['type' => 'title', 'title' => "{$clientName} Marketing Strategy", 'bullets' => ['Powered by Coral Intelligence']],
        ];

        $sections = preg_split('/^#{1,3}\s+/m', $doc, -1, PREG_SPLIT_NO_EMPTY);
        foreach (array_slice($sections, 0, 10) as $section) {
            $lines = array_filter(array_map('trim', explode("\n", trim($section))));
            $lines = array_values($lines);
            if (empty($lines)) continue;
            $title = $lines[0];
            $bullets = [];
            foreach (array_slice($lines, 1) as $line) {
                $line = preg_replace('/^[-*•]\s*/', '', $line);
                if ($line && strlen($line) > 5) $bullets[] = $line;
                if (count($bullets) >= 5) break;
            }
            if ($bullets) {
                $slides[] = ['type' => 'content', 'title' => $title, 'bullets' => $bullets];
            }
        }
        return $slides;
    }

    private function buildSlide(PhpPresentation $prs, array $data, bool $isFirst, int $total): void
    {
        $slide = $prs->createSlide();

        // Background
        $bg = new BgColor();
        $bg->setColor(new Color($isFirst ? self::NAVY : self::WHITE));
        $slide->setBackground($bg);

        $isTitle = ($data['type'] ?? 'content') === 'title';

        if ($isTitle) {
            // Full navy background, centered title
            $this->addTextBox($slide,
                text: $data['title'],
                x: 800000, y: 1500000, w: 7600000, h: 1200000,
                size: 36, bold: true, color: self::WHITE, align: Alignment::HORIZONTAL_CENTER
            );
            if (!empty($data['bullets'])) {
                $this->addTextBox($slide,
                    text: implode(' · ', $data['bullets']),
                    x: 800000, y: 2900000, w: 7600000, h: 600000,
                    size: 16, bold: false, color: self::PINK, align: Alignment::HORIZONTAL_CENTER
                );
            }
            // Pink accent line
            $line = $slide->createLineShape(800000, 2750000, 8400000, 2750000);
            $line->setLineColor(new Color(self::PINK));
            $line->setLineWidth(3);
        } else {
            // White slide: navy header bar
            $header = $slide->createRichTextShape();
            $header->setOffsetX(0)->setOffsetY(0)->setWidth(9144000)->setHeight(700000);
            $this->solidFill($header, self::NAVY);
            $run = $header->createTextRun($data['title']);
            $run->getFont()->setBold(true)->setSize(22)->setColor(new Color(self::WHITE));
            $header->getActiveParagraph()->getAlignment()
                ->setHorizontal(Alignment::HORIZONTAL_LEFT)
                ->setMarginLeft(400000);

            // Bullets
            $bullets = $data['bullets'] ?? [];
            $yStart  = 850000;
            $yStep   = 550000;
            foreach (array_slice($bullets, 0, 6) as $i => $bullet) {
                $this->addTextBox($slide,
                    text: '• ' . $bullet,
                    x: 600000, y: $yStart + $i * $yStep, w: 7900000, h: 500000,
                    size: 16, bold: false, color: self::DARK
                );
            }

            // Pink footer bar
            $footer = $slide->createRichTextShape();
            $footer->setOffsetX(0)->setOffsetY(4960000)->setWidth(9144000)->setHeight(270000);
            $this->solidFill($footer, self::PINK);
            $run = $footer->createTextRun('Coral Intelligence Platform');
            $run->getFont()->setSize(9)->setColor(new Color(self::WHITE));
            $footer->getActiveParagraph()->getAlignment()
                ->setHorizontal(Alignment::HORIZONTAL_LEFT)
                ->setMarginLeft(300000);
        }
    }

    private function solidFill($shape, string $argbColor): void
    {
        $fill = new \PhpOffice\PhpPresentation\Style\Fill();
        $fill->setFillType(\PhpOffice\PhpPresentation\Style\Fill::FILL_SOLID)
             ->setStartColor(new Color($argbColor));
        $shape->setFill($fill);
    }

    private function addTextBox($slide, string $text, int $x, int $y, int $w, int $h,
                                int $size, bool $bold, string $color, string $align = Alignment::HORIZONTAL_LEFT): void
    {
        $shape = $slide->createRichTextShape();
        $shape->setOffsetX($x)->setOffsetY($y)->setWidth($w)->setHeight($h);
        $run = $shape->createTextRun($text);
        $run->getFont()->setSize($size)->setBold($bold)->setColor(new Color($color));
        $shape->getActiveParagraph()->getAlignment()->setHorizontal($align);
    }
}
