<?php

namespace App\Http\Controllers;

use App\Models\Strategy;

class StrategyController extends Controller
{
    // ARGB color constants
    private const NAVY  = 'FF003470';
    private const PINK  = 'FFFC54AA';
    private const WHITE = 'FFFFFFFF';
    private const DARK  = 'FF1A1A2E';

    public function downloadSlides(string $id)
    {
        $strategy = Strategy::findOrFail($id);

        $user = auth()->user();
        if ($user->isClientUser()) {
            $client = $user->profile?->client;
        } else {
            $clientId = session('active_client_id');
            $client = $clientId ? \App\Models\Client::find($clientId) : null;
        }
        abort_unless($client && $strategy->client_id === $client->id, 403);

        if (!class_exists('\ZipArchive')) {
            \Illuminate\Support\Facades\Log::error('PPTX: ZipArchive not available');
            abort(500, 'ZipArchive extension required.');
        }

        if (!class_exists('\PhpOffice\PhpPresentation\PhpPresentation')) {
            \Illuminate\Support\Facades\Log::error('PPTX: PhpPresentation not available');
            abort(500, 'PhpPresentation package not found.');
        }

        try {
            $slides = $this->basicParse($strategy->generated_document ?? '', $client->name);

            $prs = new \PhpOffice\PhpPresentation\PhpPresentation();
            $prs->getDocumentProperties()
                ->setTitle("{$client->name} Strategy")
                ->setDescription('Generated by Coral');

            $prs->removeSlideByIndex(0);

            foreach ($slides as $i => $slideData) {
                $this->buildSlide($prs, $slideData, $i === 0);
            }

            $path = sys_get_temp_dir() . '/coral_' . uniqid() . '.pptx';
            $writer = \PhpOffice\PhpPresentation\IOFactory::createWriter($prs, 'PowerPoint2007');
            $writer->save($path);

            $filename = \Illuminate\Support\Str::slug($client->name . ' Strategy') . '.pptx';
            return response()->download($path, $filename, [
                'Content-Type' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
            ])->deleteFileAfterSend(true);
        } catch (\Throwable $e) {
            \Illuminate\Support\Facades\Log::error('PPTX generation failed', [
                'error'   => $e->getMessage(),
                'file'    => $e->getFile(),
                'line'    => $e->getLine(),
            ]);
            abort(500, 'Slide generation failed: ' . $e->getMessage());
        }
    }

    private function basicParse(string $doc, string $clientName): array
    {
        $slides = [
            ['type' => 'title', 'title' => "{$clientName} Marketing Strategy", 'bullets' => ['Powered by Coral Intelligence']],
        ];

        $sections = preg_split('/^#{1,3}\s+/m', $doc, -1, PREG_SPLIT_NO_EMPTY);
        foreach (array_slice($sections, 0, 10) as $section) {
            $lines = array_values(array_filter(array_map('trim', explode("\n", trim($section)))));
            if (empty($lines)) continue;
            $title   = $lines[0];
            $bullets = [];
            foreach (array_slice($lines, 1) as $line) {
                $line = preg_replace('/^[-*•]\s*/', '', $line);
                if ($line && strlen($line) > 5) $bullets[] = $line;
                if (count($bullets) >= 5) break;
            }
            if ($bullets) {
                $slides[] = ['type' => 'content', 'title' => $title, 'bullets' => $bullets];
            }
        }
        return $slides;
    }

    private function buildSlide(\PhpOffice\PhpPresentation\PhpPresentation $prs, array $data, bool $isFirst): void
    {
        $slide = $prs->createSlide();

        $bg = new \PhpOffice\PhpPresentation\Slide\Background\Color();
        $bg->setColor(new \PhpOffice\PhpPresentation\Style\Color($isFirst ? self::NAVY : self::WHITE));
        $slide->setBackground($bg);

        $isTitle = ($data['type'] ?? 'content') === 'title';

        if ($isTitle) {
            $this->addText($slide, $data['title'],
                800000, 1500000, 7600000, 1200000,
                36, true, self::WHITE, \PhpOffice\PhpPresentation\Style\Alignment::HORIZONTAL_CENTER
            );
            if (!empty($data['bullets'])) {
                $this->addText($slide, implode(' · ', $data['bullets']),
                    800000, 2900000, 7600000, 600000,
                    16, false, self::PINK, \PhpOffice\PhpPresentation\Style\Alignment::HORIZONTAL_CENTER
                );
            }
            $line = $slide->createLineShape(800000, 2750000, 8400000, 2750000);
            $line->setLineColor(new \PhpOffice\PhpPresentation\Style\Color(self::PINK));
            $line->setLineWidth(3);
        } else {
            $header = $slide->createRichTextShape();
            $header->setOffsetX(0)->setOffsetY(0)->setWidth(9144000)->setHeight(700000);
            $this->setFill($header, self::NAVY);
            $run = $header->createTextRun($data['title']);
            $run->getFont()->setBold(true)->setSize(22)
                ->setColor(new \PhpOffice\PhpPresentation\Style\Color(self::WHITE));
            $header->getActiveParagraph()->getAlignment()
                ->setHorizontal(\PhpOffice\PhpPresentation\Style\Alignment::HORIZONTAL_LEFT)
                ->setMarginLeft(400000);

            $yStart = 850000;
            $yStep  = 550000;
            foreach (array_slice($data['bullets'] ?? [], 0, 6) as $i => $bullet) {
                $this->addText($slide, '• ' . $bullet,
                    600000, $yStart + $i * $yStep, 7900000, 500000,
                    16, false, self::DARK
                );
            }

            $footer = $slide->createRichTextShape();
            $footer->setOffsetX(0)->setOffsetY(4960000)->setWidth(9144000)->setHeight(270000);
            $this->setFill($footer, self::PINK);
            $run = $footer->createTextRun('Coral Intelligence Platform');
            $run->getFont()->setSize(9)->setColor(new \PhpOffice\PhpPresentation\Style\Color(self::WHITE));
            $footer->getActiveParagraph()->getAlignment()
                ->setHorizontal(\PhpOffice\PhpPresentation\Style\Alignment::HORIZONTAL_LEFT)
                ->setMarginLeft(300000);
        }
    }

    private function setFill($shape, string $argb): void
    {
        $fill = new \PhpOffice\PhpPresentation\Style\Fill();
        $fill->setFillType(\PhpOffice\PhpPresentation\Style\Fill::FILL_SOLID)
             ->setStartColor(new \PhpOffice\PhpPresentation\Style\Color($argb));
        $shape->setFill($fill);
    }

    private function addText($slide, string $text, int $x, int $y, int $w, int $h,
                             int $size, bool $bold, string $color,
                             string $align = \PhpOffice\PhpPresentation\Style\Alignment::HORIZONTAL_LEFT): void
    {
        $shape = $slide->createRichTextShape();
        $shape->setOffsetX($x)->setOffsetY($y)->setWidth($w)->setHeight($h);
        $run = $shape->createTextRun($text);
        $run->getFont()->setSize($size)->setBold($bold)
            ->setColor(new \PhpOffice\PhpPresentation\Style\Color($color));
        $shape->getActiveParagraph()->getAlignment()->setHorizontal($align);
    }
}
