<?php

namespace App\Http\Controllers;

use App\Models\Strategy;

class StrategyController extends Controller
{
    private const NAVY  = 'FF003470';
    private const PINK  = 'FFFC54AA';
    private const WHITE = 'FFFFFFFF';
    private const DARK  = 'FF1A1A2E';

    public function downloadSlides(string $id)
    {
        $strategy = Strategy::findOrFail($id);

        $user = auth()->user();
        if ($user->isClientUser()) {
            $client = $user->profile?->client;
        } else {
            $clientId = session('active_client_id');
            $client = $clientId ? \App\Models\Client::find($clientId) : null;
        }

        if (!$client || $strategy->client_id !== $client->id) {
            abort(403);
        }

        try {
            $slides = $this->parseSlides($strategy->generated_document ?? '', $client->name);

            $prs = new \PhpOffice\PhpPresentation\PhpPresentation();
            $prs->getDocumentProperties()
                ->setTitle("{$client->name} Strategy")
                ->setDescription('Generated by Coral');
            $prs->removeSlideByIndex(0);

            foreach ($slides as $i => $slideData) {
                $this->buildSlide($prs, $slideData, $i === 0);
            }

            $path = sys_get_temp_dir() . '/coral_' . uniqid() . '.pptx';
            \PhpOffice\PhpPresentation\IOFactory::createWriter($prs, 'PowerPoint2007')->save($path);

            $filename = \Illuminate\Support\Str::slug($client->name . ' Strategy') . '.pptx';
            return response()->download($path, $filename, [
                'Content-Type' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
            ])->deleteFileAfterSend(true);
        } catch (\Throwable $e) {
            \Illuminate\Support\Facades\Log::error('PPTX error', ['msg' => $e->getMessage(), 'file' => $e->getFile(), 'line' => $e->getLine()]);
            abort(500, $e->getMessage());
        }
    }

    private function parseSlides(string $doc, string $clientName): array
    {
        try {
            $prompt = "Convert this marketing strategy document into a slide deck for {$clientName}. "
                . "Return a JSON array of slides. Each slide: {\"type\":\"title\" or \"content\", \"title\":\"...\", \"bullets\":[\"...\",\"...\"]}. "
                . "First slide is type title with client name and one subtitle bullet. "
                . "Create 8-12 content slides covering key sections. 3-5 bullets per slide, each bullet max 12 words. "
                . "Return ONLY valid JSON array, no markdown fences.\n\nDOCUMENT:\n" . mb_substr($doc, 0, 5000);

            $response = app(\Anthropic\Client::class)->messages->create(
                maxTokens: 2000,
                messages: [['role' => 'user', 'content' => $prompt]],
                model: 'claude-haiku-4-5-20251001',
            );
            $json   = trim($response->content[0]->text ?? '');
            $json   = preg_replace('/^```(?:json)?\s*/m', '', $json);
            $json   = preg_replace('/\s*```\s*$/m', '', $json);
            $slides = json_decode(trim($json), true);
            if (is_array($slides) && count($slides) >= 2) {
                return $slides;
            }
        } catch (\Throwable $e) {
            // Fall through to basic parse
        }
        return $this->basicParse($doc, $clientName);
    }

    private function basicParse(string $doc, string $clientName): array
    {
        $slides = [
            ['type' => 'title', 'title' => "{$clientName} Marketing Strategy", 'bullets' => ['Powered by Coral Intelligence']],
        ];

        $sections = preg_split('/^#{1,3}\s+/m', $doc, -1, PREG_SPLIT_NO_EMPTY);
        foreach (array_slice($sections, 0, 10) as $section) {
            $lines = array_values(array_filter(array_map('trim', explode("\n", trim($section)))));
            if (empty($lines)) continue;
            $title   = $lines[0];
            $bullets = [];
            foreach (array_slice($lines, 1) as $line) {
                $line = preg_replace('/^[-*•]\s*/', '', $line);
                if ($line && strlen($line) > 5) $bullets[] = $line;
                if (count($bullets) >= 5) break;
            }
            if ($bullets) {
                $slides[] = ['type' => 'content', 'title' => $title, 'bullets' => $bullets];
            }
        }
        return $slides;
    }

    private function buildSlide(\PhpOffice\PhpPresentation\PhpPresentation $prs, array $data, bool $isFirst): void
    {
        $slide = $prs->createSlide();

        // Always set an explicit white background; title slide overrides to navy
        $bg = new \PhpOffice\PhpPresentation\Slide\Background\Color();
        $bg->setColor(new \PhpOffice\PhpPresentation\Style\Color(self::WHITE));
        $slide->setBackground($bg);

        $isTitle = ($data['type'] ?? 'content') === 'title';

        if ($isTitle) {
            // Navy background for title slide
            $bgNav = new \PhpOffice\PhpPresentation\Slide\Background\Color();
            $bgNav->setColor(new \PhpOffice\PhpPresentation\Style\Color(self::NAVY));
            $slide->setBackground($bgNav);

            // Title
            $this->addText($slide, $data['title'],
                600000, 1800000, 7900000, 1400000, 36, true, self::WHITE, 'ctr');

            // Subtitle bullets as one line in pink
            if (!empty($data['bullets'])) {
                $subtitle = is_array($data['bullets']) ? implode(' · ', array_map('strval', $data['bullets'])) : '';
                if ($subtitle) {
                    $this->addText($slide, $subtitle,
                        600000, 3400000, 7900000, 600000, 18, false, self::PINK, 'ctr');
                }
            }
        } else {
            // Navy header bar
            $header = $slide->createRichTextShape();
            $header->setOffsetX(0)->setOffsetY(0)->setWidth(9144000)->setHeight(800000);
            $this->setFill($header, self::NAVY);
            $run = $header->createTextRun(strval($data['title'] ?? ''));
            $run->getFont()->setBold(true)->setSize(24)
                ->setColor(new \PhpOffice\PhpPresentation\Style\Color(self::WHITE));
            $header->getActiveParagraph()->getAlignment()
                ->setHorizontal('l')->setMarginLeft(500000);

            // Bullet points
            $bullets = array_slice(array_filter(array_map('strval', $data['bullets'] ?? [])), 0, 6);
            $yStart  = 950000;
            $yStep   = 600000;
            foreach (array_values($bullets) as $i => $bullet) {
                $this->addText($slide, '• ' . $bullet,
                    500000, $yStart + $i * $yStep, 8100000, 560000, 18, false, self::DARK);
            }

            // Pink footer bar
            $footer = $slide->createRichTextShape();
            $footer->setOffsetX(0)->setOffsetY(4870000)->setWidth(9144000)->setHeight(280000);
            $this->setFill($footer, self::PINK);
            $run = $footer->createTextRun('Coral Intelligence Platform');
            $run->getFont()->setSize(10)->setColor(new \PhpOffice\PhpPresentation\Style\Color(self::WHITE));
            $footer->getActiveParagraph()->getAlignment()
                ->setHorizontal('l')->setMarginLeft(400000);
        }
    }

    private function setFill($shape, string $argb): void
    {
        $fill = new \PhpOffice\PhpPresentation\Style\Fill();
        $fill->setFillType(\PhpOffice\PhpPresentation\Style\Fill::FILL_SOLID)
             ->setStartColor(new \PhpOffice\PhpPresentation\Style\Color($argb));
        $shape->setFill($fill);
    }

    private function addText($slide, string $text, int $x, int $y, int $w, int $h,
                             int $size, bool $bold, string $color, string $align = 'l'): void
    {
        $shape = $slide->createRichTextShape();
        $shape->setOffsetX($x)->setOffsetY($y)->setWidth($w)->setHeight($h);
        $run = $shape->createTextRun($text);
        $run->getFont()->setSize($size)->setBold($bold)
            ->setColor(new \PhpOffice\PhpPresentation\Style\Color($color));
        $shape->getActiveParagraph()->getAlignment()->setHorizontal($align);
    }
}
